### ISSUE TITLE
关于是否能够移植到其他区服？

### ISSUE THREAD

**Issue by kumonohayaku** [qq1176321897/pcrjjc2#10]
虽然dalao的插件是适用于国服环境的，那么能付移植到台服或者日服使用呢？通过台服游戏数据发现和国服的文件有所不同，目录下应该仅有UnityPlayer.xml这个是有效文件，并没有key之类的字样，目前移植的可能性大吗？

**Comment by qq1176321897** [comment]
@lulu666lulu

**Comment by lulu666lulu** [comment]
？

**Comment by qq1176321897** [comment]
草为什么会close失败啊！
