### ISSUE TITLE
关于私聊

### ISSUE THREAD

**Issue by Grampus2012** [qq1176321897/pcrjjc2#17]
您好，可以了解下新版没有保留旧版私聊推送排名功能的原因吗？目前用户人数70人，只允许公屏推送比较扰屏

**Comment by qq1176321897** [comment]
与其说没有保留 不如说[旧版](https://github.com/lulu666lulu/pcrjjc)并没有这个功能

**Comment by Grampus2012** [comment]
感谢，我自己借鉴下别人的代码

**Comment by qq1176321897** [comment]
（？最后一次更新已经改成私聊了
