### ISSUE TITLE
在on_arena_schedule定时任务启动的时候 触发竞技场查询命令将会二选一执行

### ISSUE THREAD

**Issue by wosiwq** [qq1176321897/pcrjjc2#2]
在更新了今天最新commit的版本之后 再进行复现的时候发现要么会把竞技场查询的命令卡没 要么会把这次的查询卡没
![image](https://user-images.githubusercontent.com/45610776/104448821-926c6f00-5595-11eb-820d-204455eda552.png) 顺便一提 定时任务可以用秒 seconds （

**Comment by wosiwq** [comment]
timeout那个是我的误判 其实就是这两个冲突了直接卡死了

**Comment by qq1176321897** [comment]
在f965191中应该已经修复

**Comment by wosiwq** [comment]
我现在用的是dae00f7实测还是有问题 只是不再会卡死 而是变成两个其中执行一个
![image](https://user-images.githubusercontent.com/45610776/104468307-37e00c80-55af-11eb-9a7f-6fc6b2bebc95.png)

**Comment by qq1176321897** [comment]
这个问题。。。查询和定时似乎不能用asyncio进行互斥，但是查询之间只能用asyncio进行互斥，并不会解决（wtcl）而且也没什么大影响就放一放吧（

**Comment by wosiwq** [comment]
当用户少的时候确实没什么大影响，但是当用户多起来的时候，多加几个jjc的群，就会让on_arena_schedule运行所消耗的时间变长，如果又在此基础上，将任务时间缩短为每半分钟一次(比如我)(对不起)，那么触发的几率将会大大增加，如果真的多到连续不间断的都在查询的话，那就相当于查询这个命令直接废了。话说print出来会不会增加耗时？

**Comment by qq1176321897** [comment]
应该已经在https://github.com/qq1176321897/pcrjjc2/commit/ad107267b3d58b318dd3c0f7fed485dce2fca234 中修复

**Comment by wosiwq** [comment]
我不知道在 ad10726 之后问题有没有修复，在更新到 ad10726 之后出现了以下的几个问题

1. 在`Scheduled job on_arena_schedule completed.`之后还有一条查询 `pcrclient: /profile/get_profile api called`，并且推送排名变得不准确，怀疑是顺移了一位，这导致了在订阅列表最后的一位被轮番轰炸
2. 在第一轮completed之后 第二轮start之后没有动静，连get_profile都不会弹出，等到第三轮start会提示队列满了，5秒之后尝试，然后5秒后才会开始滚动get_profile，并且之后也是不是出现队列满的提示

因为上面的原因，我无法测试是否在 ad10726 中修复了这个bug，这个commit引入了更多的BUG，让我无法确定到底是什么造成的

**Comment by qq1176321897** [comment]
那个实现非常糟糕（其实我是准备新建branch但是操作错了）你可以试试最新的一版（哦发现好像没传上去 明天等我重新push一下）

**Comment by wosiwq** [comment]
经测试 ba0c644 版本已经修复了这个问题，不过出现了新的问题，在使用ctrl+c结束程序而不是关闭整个powershell窗口再重新打开的时候，第二次run起来并不会重新启动一个新的loop，或者说，在创建loop之前并没有尝试关闭掉之前有可能残余的loop，导致有些许冲突问题

**Comment by qq1176321897** [comment]
我想这个应该不是插件的问题，我没有新建任何新的loop 我觉得还是应该结束的时候确认已经终止所有py进程

**Comment by wosiwq** [comment]
此问题已在 ba0c644 修复
