### ISSUE TITLE
私聊排名变化消息收不到

### ISSUE THREAD

**Issue by 666dechaoge** [qq1176321897/pcrjjc2#20]
改私聊后排名变化消息收不到

**Comment by qq1176321897** [comment]
确认是否加过好友
现在私聊已经移入private分支，回滚了之前对版本号的更改，可以试试重新从private分支pull

**Comment by 666dechaoge** [comment]
![image](https://user-images.githubusercontent.com/49865203/113553100-c9e53780-9629-11eb-93fc-06a3123a1d41.png)
您似乎把id与uid好像搞混了

**Comment by 666dechaoge** [comment]
id是游戏ID，uid是QQ号？

**Comment by qq1176321897** [comment]
哦 是这样
