### ISSUE TITLE
账号异常，要求去主站验证

### ISSUE THREAD

**Issue by 666dechaoge** [qq1176321897/pcrjjc2#21]
pcrjjc2登录错误：系统检测到您的账号异常，请前往网页主站重新登录并进行验证
一直用了两个月，今天提示这个了
出问题后bot并没有及时报错，我晚上手动查排名失败才知道出问题了，换了个号没事了

**Comment by 666dechaoge** [comment]
具体就是：按往常一样查排名，报错：查询出错，发生了错误。\n回到标题界面。
于是重启bot重新登录，过了验证码，紧接着报错：pcrjjc2登录错误：系统检测到您的账号异常，请前往网页主站重新登录并进行验证
这才知道号出问题了

**Comment by qq1176321897** [comment]
请和我一起吟唱：b站傻逼 陈睿傻逼
