### ISSUE TITLE
验证码链接无法打开，无法完成验证

### ISSUE THREAD

**Issue by wmxzqq** [qq1176321897/pcrjjc2#27]
已确认国内国外ip均无法打开，请问是否为网站问题？

**Comment by qq1176321897** [comment]
@lulu666lulu

**Comment by qq1176321897** [comment]
cdn问题 你可以暂时用`http://pcr.zfjdhj.cn/geetest/captcha/`替换前面部分

**Comment by wmxzqq** [comment]
替换后验证可用，感谢解答。

**Comment by WindStill** [comment]
> cdn问题 你可以暂时用`http://pcr.zfjdhj.cn/geetest/captcha/`替换前面部分

这个也打不开

**Comment by cc004** [comment]
> > cdn问题 你可以暂时用`http://pcr.zfjdhj.cn/geetest/captcha/`替换前面部分
> 
> 这个也打不开

我可以

**Comment by lulu666lulu** [comment]
？

**Comment by lulu666lulu** [comment]
哦，cdn欠费了
