### ISSUE TITLE
powershell与cmd内行为与预期不符

### ISSUE THREAD

**Issue by wosiwq** [qq1176321897/pcrjjc2#5]
在#2这个issue中提交的那个问题，经过我测试之后，发现是powershell的问题 在使用powershell ctrl+c 或者直接使用powershell `python run.py` 均会触发loop异常的报错 cmd内则不会，我直接人麻了

**Comment by wosiwq** [comment]
cmd内ctrl+c也会 刚试了下 而powershell是直接用不了了（

**Comment by qq1176321897** [comment]
至少先发下报错内容吧

**Comment by wosiwq** [comment]
![image](https://user-images.githubusercontent.com/45610776/106095931-93bca080-612c-11eb-8ef5-6dbb75ffbc8b.png)
抱歉抱歉 最近有些忙

**Comment by wosiwq** [comment]
![image](https://user-images.githubusercontent.com/45610776/106096721-ff533d80-612d-11eb-85f9-674569e68e2f.png)
这是进程 单独启动也会出现这个问题
![image](https://user-images.githubusercontent.com/45610776/106096791-1abe4880-612e-11eb-9dd3-3fca238aa3c1.png)
服务器用的是aliyun的轻量 win server 2012 python版本是3.8.3

**Comment by qq1176321897** [comment]
你这个是因为间隔设置的太小，上一次schedule没完成就开始下一次了，不是插件错误

**Comment by wosiwq** [comment]
我间隔没问题 正常使用一点问题都没有 只有快速关闭启动的时候会出现

**Comment by wosiwq** [comment]
今天是7.30，实测在同一环境下还是可以稳定复现，均是重启后出现，在出现此条提示之后往后所有的查询都会提示这个报错，无法正常使用任何功能，我觉得需要一个能实时交流的联系方式来交流这个问题

**Comment by cc004** [comment]
大概是没输验证码吧

**Comment by wosiwq** [comment]
我录制了一个视频来复现我的操作，可以看到整个系统大重启之后依旧无法正常使用插件，均确保是最新的commit，未修改任何代码
[20210730-133939652.zip](https://github.com/cc004/pcrjjc2/files/6905319/20210730-133939652.zip)

**Comment by wosiwq** [comment]
> 大概是没输验证码吧

1000%不是 连验证码都没到呢就卡死了（

**Comment by cc004** [comment]
> 我录制了一个视频来复现我的操作，可以看到整个系统大重启之后依旧无法正常使用插件，均确保是最新的commit，未修改任何代码
> [20210730-133939652.zip](https://github.com/cc004/pcrjjc2/files/6905319/20210730-133939652.zip)

这不是根本没卡死吗，你给查询函数前面加个print看看执行没

**Comment by wosiwq** [comment]
> > 我录制了一个视频来复现我的操作，可以看到整个系统大重启之后依旧无法正常使用插件，均确保是最新的commit，未修改任何代码
> > [20210730-133939652.zip](https://github.com/cc004/pcrjjc2/files/6905319/20210730-133939652.zip)
> 
> 这不是根本没卡死吗，你给查询函数前面加个print看看执行没

卡死说的是 永远无限循环这一条 走不下去了 
![image](https://user-images.githubusercontent.com/45610776/127608089-ea6e13cd-1298-4009-b104-579dd7eb0ae5.png)

**Comment by cc004** [comment]
> > > 我录制了一个视频来复现我的操作，可以看到整个系统大重启之后依旧无法正常使用插件，均确保是最新的commit，未修改任何代码
> > > [20210730-133939652.zip](https://github.com/cc004/pcrjjc2/files/6905319/20210730-133939652.zip)
> > 
> > 
> > 这不是根本没卡死吗，你给查询函数前面加个print看看执行没
> 
> 卡死说的是 永远无限循环这一条 走不下去了
> ![image](https://user-images.githubusercontent.com/45610776/127608089-ea6e13cd-1298-4009-b104-579dd7eb0ae5.png)

我只能建议你多加几个print看看卡死在哪里
