### ISSUE TITLE
在某些情况下插件无法进行查询

### ISSUE THREAD

**Issue by CCA2878** [qq1176321897/pcrjjc2#8]
应该是前几天，感觉是不是B站搞了什么鬼，对于某一个用于查询的账号会突然无法查询，无法获取信息。
具体表现是开始查询的计划任务后就停留在第一个需要查询的号，然后就没有然后，一直停在那。
更换用于查询的账号有概率解决，但是一段时间之后也会出现类似情况……

**Comment by qq1176321897** [comment]
jjc1后端从来没有这个问题，建议不要用白板小号或者游客号，把等级提高一点
据说出现这种情况的时候sdk login会返回is_risk=1，你可以自己判断一下

**Comment by CCA2878** [comment]
> jjc1后端从来没有这个问题，建议不要用白板小号或者游客号，把等级提高一点
> 据说出现这种情况的时候sdk login会返回is_risk=1，你可以自己判断一下

我目前用的是某宝一两块一个的自抽号，等级普遍40级左右。
既然SDK能反应risk的情况，准备这两天写个自动切换，要是好用的话会考虑交PR。

**Comment by zangxx66** [comment]
最近B站对此类账号做了登录验证码处理，需要在模拟器或手机端完成一次验证后可恢复，既然客户端可以弹出图片验证，那么有没有办法模拟客户端验证

**Comment by CCA2878** [comment]
> 最近B站对此类账号做了登录验证码处理，需要在模拟器或手机端完成一次验证后可恢复，既然客户端可以弹出图片验证，那么有没有办法模拟客户端验证

要是能这样那设计验证码的人可以滚蛋了（滑稽）。验证码的目的就是防范这种机器脚本。
我的思路是支持账号池，然后如果有失效的自动切换并且提醒管理员。
当然现在在打会战，这方面魔改就先摸了。

**Comment by zangxx66** [comment]
> > 最近B站对此类账号做了登录验证码处理，需要在模拟器或手机端完成一次验证后可恢复，既然客户端可以弹出图片验证，那么有没有办法模拟客户端验证
> 
> 要是能这样那设计验证码的人可以滚蛋了（滑稽）。验证码的目的就是防范这种机器脚本。
> 我的思路是支持账号池，然后如果有失效的自动切换并且提醒管理员。
> 当然现在在打会战，这方面魔改就先摸了。

服务器维护和账号失效的status都是3，自动切换需要识别返回的message是什么内容（滑稽）

**Comment by CCA2878** [comment]
> > > 最近B站对此类账号做了登录验证码处理，需要在模拟器或手机端完成一次验证后可恢复，既然客户端可以弹出图片验证，那么有没有办法模拟客户端验证
> > 
> > 
> > 要是能这样那设计验证码的人可以滚蛋了（滑稽）。验证码的目的就是防范这种机器脚本。
> > 我的思路是支持账号池，然后如果有失效的自动切换并且提醒管理员。
> > 当然现在在打会战，这方面魔改就先摸了。
> 
> 服务器维护和账号失效的status都是3，自动切换需要识别返回的message是什么内容（滑稽）

不知哪能有SDK的相关文档……

**Comment by clacknya** [comment]
已经出现好几次跳验证的情况了……


> 
> 
> jjc1后端从来没有这个问题，建议不要用白板小号或者游客号，把等级提高一点
> 据说出现这种情况的时候sdk login会返回is_risk=1，你可以自己判断一下

能否添加一个出现 risk 就通知主人的功能？

**Comment by qq1176321897** [comment]
> 已经出现好几次跳验证的情况了……
> 
> > jjc1后端从来没有这个问题，建议不要用白板小号或者游客号，把等级提高一点
> > 据说出现这种情况的时候sdk login会返回is_risk=1，你可以自己判断一下
> 
> 能否添加一个出现 risk 就通知主人的功能？

你甚至可以自己写！
这个大概我不会考虑去写因为我无论哪个号都没risk。。。所以没办法测试
如果你pr的话我会很高兴的去merge（

**Comment by CCA2878** [comment]
> > 已经出现好几次跳验证的情况了……
> > > jjc1后端从来没有这个问题，建议不要用白板小号或者游客号，把等级提高一点
> > > 据说出现这种情况的时候sdk login会返回is_risk=1，你可以自己判断一下
> > 
> > 
> > 能否添加一个出现 risk 就通知主人的功能？
> 
> 你甚至可以自己写！
> 这个大概我不会考虑去写因为我无论哪个号都没risk。。。所以没办法测试
> 如果你pr的话我会很高兴的去merge（

所以想问问有没有b站这SDK方面的资料提供一下
现有代码无注释是真难啃……

**Comment by qq1176321897** [comment]
> > > 已经出现好几次跳验证的情况了……
> > > > jjc1后端从来没有这个问题，建议不要用白板小号或者游客号，把等级提高一点
> > > > 据说出现这种情况的时候sdk login会返回is_risk=1，你可以自己判断一下
> > > 
> > > 
> > > 能否添加一个出现 risk 就通知主人的功能？
> > 
> > 
> > 你甚至可以自己写！
> > 这个大概我不会考虑去写因为我无论哪个号都没risk。。。所以没办法测试
> > 如果你pr的话我会很高兴的去merge（
> 
> 所以想问问有没有b站这SDK方面的资料提供一下
> 现有代码无注释是真难啃……

 如果你指的是bsgamesdk大概https://github.com/Kengxxiao/Chika下就有，如果你指的是chika的注释的话emmm不知道

**Comment by CCA2878** [comment]
> > > > 已经出现好几次跳验证的情况了……
> > > > > jjc1后端从来没有这个问题，建议不要用白板小号或者游客号，把等级提高一点
> > > > > 据说出现这种情况的时候sdk login会返回is_risk=1，你可以自己判断一下
> > > > 
> > > > 
> > > > 能否添加一个出现 risk 就通知主人的功能？
> > > 
> > > 
> > > 你甚至可以自己写！
> > > 这个大概我不会考虑去写因为我无论哪个号都没risk。。。所以没办法测试
> > > 如果你pr的话我会很高兴的去merge（
> > 
> > 
> > 所以想问问有没有b站这SDK方面的资料提供一下
> > 现有代码无注释是真难啃……
> 
> 如果你指的是bsgamesdk大概https://github.com/Kengxxiao/Chika 下就有，如果你指的是chika的注释的话emmm不知道

猛然发现：http://open.biligame.com/wiki/
那没事了，文档有了。无聊的寒假就来研究研究。
另外chika对付geetest的方法是接入打码平台，不过个人还是倾向不使用过多第三方服务。

**Comment by CCA2878** [comment]
> > > > 已经出现好几次跳验证的情况了……
> > > > > jjc1后端从来没有这个问题，建议不要用白板小号或者游客号，把等级提高一点
> > > > > 据说出现这种情况的时候sdk login会返回is_risk=1，你可以自己判断一下
> > > > 
> > > > 
> > > > 能否添加一个出现 risk 就通知主人的功能？
> > > 
> > > 
> > > 你甚至可以自己写！
> > > 这个大概我不会考虑去写因为我无论哪个号都没risk。。。所以没办法测试
> > > 如果你pr的话我会很高兴的去merge（
> > 
> > 
> > 所以想问问有没有b站这SDK方面的资料提供一下
> > 现有代码无注释是真难啃……
> 
> 如果你指的是bsgamesdk大概https://github.com/Kengxxiao/Chika 下就有，如果你指的是chika的注释的话emmm不知道

大意了，B站官方文档对验证码只字未提。
只能慢慢啃了……

**Comment by Kengxxiao** [comment]
> > > > > 已经出现好几次跳验证的情况了……
> > > > > > jjc1后端从来没有这个问题，建议不要用白板小号或者游客号，把等级提高一点
> > > > > > 据说出现这种情况的时候sdk login会返回is_risk=1，你可以自己判断一下
> > > > > 
> > > > > 
> > > > > 能否添加一个出现 risk 就通知主人的功能？
> > > > 
> > > > 
> > > > 你甚至可以自己写！
> > > > 这个大概我不会考虑去写因为我无论哪个号都没risk。。。所以没办法测试
> > > > 如果你pr的话我会很高兴的去merge（
> > > 
> > > 
> > > 所以想问问有没有b站这SDK方面的资料提供一下
> > > 现有代码无注释是真难啃……
> > 
> > 
> > 如果你指的是bsgamesdk大概https://github.com/Kengxxiao/Chika 下就有，如果你指的是chika的注释的话emmm不知道
> 
> 猛然发现：http://open.biligame.com/wiki/
> 那没事了，文档有了。无聊的寒假就来研究研究。
> 另外chika对付geetest的方法是接入打码平台，不过个人还是倾向不使用过多第三方服务。

当然可以不接入打码平台，自己进验证码页面，像mirai抓包过滑块一样。但是Chika搞这个的目的是掉线重连，所以用了这种自动的方式。

**Comment by CCA2878** [comment]
QQ的滑块本质上还是web页面，但是geetest则是集成到SDK中，抓包复杂度比web大得多，不太可能采用这种方法。
owner提出的检测到risk的时候通知机器人管理员手动登陆做验证码算目前最可行的，但是要解决游戏维护的判断问题，不然到时候能烦死管理员……



---原始邮件---
发件人: "Kengxxiao"<notifications@github.com&gt;
发送时间: 2021年2月13日(周六) 晚上6:21
收件人: "qq1176321897/pcrjjc2"<pcrjjc2@noreply.github.com&gt;;
抄送: "CCA2878"<1054331608@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [qq1176321897/pcrjjc2] 在某些情况下插件无法进行查询 (#8)




      
已经出现好几次跳验证的情况了……
  
jjc1后端从来没有这个问题，建议不要用白板小号或者游客号，把等级提高一点
 据说出现这种情况的时候sdk login会返回is_risk=1，你可以自己判断一下
  
能否添加一个出现 risk 就通知主人的功能？
  
你甚至可以自己写！
 这个大概我不会考虑去写因为我无论哪个号都没risk。。。所以没办法测试
 如果你pr的话我会很高兴的去merge（
  
所以想问问有没有b站这SDK方面的资料提供一下
 现有代码无注释是真难啃……
  
如果你指的是bsgamesdk大概https://github.com/Kengxxiao/Chika 下就有，如果你指的是chika的注释的话emmm不知道
  
猛然发现：http://open.biligame.com/wiki/
 那没事了，文档有了。无聊的寒假就来研究研究。
 另外chika对付geetest的方法是接入打码平台，不过个人还是倾向不使用过多第三方服务。
  
当然可以不接入打码平台，自己进验证码页面，像mirai抓包过滑块一样。但是Chika搞这个的目的是掉线重连，所以用了这种自动的方式。

**Comment by Kengxxiao** [comment]
> QQ的滑块本质上还是web页面，但是geetest则是集成到SDK中，抓包复杂度比web大得多，不太可能采用这种方法。 owner提出的检测到risk的时候通知机器人管理员手动登陆做验证码算目前最可行的，但是要解决游戏维护的判断问题，不然到时候能烦死管理员……
> […](#)
> ---原始邮件--- 发件人: "Kengxxiao"<notifications@github.com&gt; 发送时间: 2021年2月13日(周六) 晚上6:21 收件人: "qq1176321897/pcrjjc2"<pcrjjc2@noreply.github.com&gt;; 抄送: "CCA2878"<1054331608@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题: Re: [qq1176321897/pcrjjc2] 在某些情况下插件无法进行查询 (#8) 已经出现好几次跳验证的情况了…… jjc1后端从来没有这个问题，建议不要用白板小号或者游客号，把等级提高一点 据说出现这种情况的时候sdk login会返回is_risk=1，你可以自己判断一下 能否添加一个出现 risk 就通知主人的功能？ 你甚至可以自己写！ 这个大概我不会考虑去写因为我无论哪个号都没risk。。。所以没办法测试 如果你pr的话我会很高兴的去merge（ 所以想问问有没有b站这SDK方面的资料提供一下 现有代码无注释是真难啃…… 如果你指的是bsgamesdk大概https://github.com/Kengxxiao/Chika 下就有，如果你指的是chika的注释的话emmm不知道 猛然发现：http://open.biligame.com/wiki/ 那没事了，文档有了。无聊的寒假就来研究研究。 另外chika对付geetest的方法是接入打码平台，不过个人还是倾向不使用过多第三方服务。 当然可以不接入打码平台，自己进验证码页面，像mirai抓包过滑块一样。但是Chika搞这个的目的是掉线重连，所以用了这种自动的方式。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

geetest也是一个web页面。
可以参考Chika代码里提供的referer参数，那个就是验证码页面，结果由geetest api返回。

**Comment by qq1176321897** [comment]
> > QQ的滑块本质上还是web页面，但是geetest则是集成到SDK中，抓包复杂度比web大得多，不太可能采用这种方法。 owner提出的检测到risk的时候通知机器人管理员手动登陆做验证码算目前最可行的，但是要解决游戏维护的判断问题，不然到时候能烦死管理员……
> > […](#)
> > ---原始邮件--- 发件人: "Kengxxiao"<[notifications@github.com](mailto:notifications@github.com)> 发送时间: 2021年2月13日(周六) 晚上6:21 收件人: "qq1176321897/pcrjjc2"<[pcrjjc2@noreply.github.com](mailto:pcrjjc2@noreply.github.com)>; 抄送: "CCA2878"<[1054331608@qq.com](mailto:1054331608@qq.com)>;"Author"<[author@noreply.github.com](mailto:author@noreply.github.com)>; 主题: Re: [qq1176321897/pcrjjc2] 在某些情况下插件无法进行查询 (#8) 已经出现好几次跳验证的情况了…… jjc1后端从来没有这个问题，建议不要用白板小号或者游客号，把等级提高一点 据说出现这种情况的时候sdk login会返回is_risk=1，你可以自己判断一下 能否添加一个出现 risk 就通知主人的功能？ 你甚至可以自己写！ 这个大概我不会考虑去写因为我无论哪个号都没risk。。。所以没办法测试 如果你pr的话我会很高兴的去merge（ 所以想问问有没有b站这SDK方面的资料提供一下 现有代码无注释是真难啃…… 如果你指的是bsgamesdk大概https://github.com/Kengxxiao/Chika 下就有，如果你指的是chika的注释的话emmm不知道 猛然发现：http://open.biligame.com/wiki/ 那没事了，文档有了。无聊的寒假就来研究研究。 另外chika对付geetest的方法是接入打码平台，不过个人还是倾向不使用过多第三方服务。 当然可以不接入打码平台，自己进验证码页面，像mirai抓包过滑块一样。但是Chika搞这个的目的是掉线重连，所以用了这种自动的方式。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> geetest也是一个web页面。
> 可以参考Chika代码里向打码平台请求提供的referer参数，那个就是验证码页面，结果由geetest api返回。

确实是web界面，不过刚才我拿f12看了一下，他游戏内验证码界面中的 https://static.biligame.com/sdk/geetest/js/captcha.js 会把geetest的validate结果以`window.webkit.messageHandlers.BiliJsObject.postMessage`的方式返回，这样似乎除了用专用浏览器或者f12打开页面完成验证，还想不到更好的办法把验证传给机器人？（当然指的是管理员手动打开验证界面，不是用第三方服务进行验证处理）

**Comment by Kengxxiao** [comment]
> > > QQ的滑块本质上还是web页面，但是geetest则是集成到SDK中，抓包复杂度比web大得多，不太可能采用这种方法。 owner提出的检测到risk的时候通知机器人管理员手动登陆做验证码算目前最可行的，但是要解决游戏维护的判断问题，不然到时候能烦死管理员……
> > > […](#)
> > > ---原始邮件--- 发件人: "Kengxxiao"<[notifications@github.com](mailto:notifications@github.com)> 发送时间: 2021年2月13日(周六) 晚上6:21 收件人: "qq1176321897/pcrjjc2"<[pcrjjc2@noreply.github.com](mailto:pcrjjc2@noreply.github.com)>; 抄送: "CCA2878"<[1054331608@qq.com](mailto:1054331608@qq.com)>;"Author"<[author@noreply.github.com](mailto:author@noreply.github.com)>; 主题: Re: [qq1176321897/pcrjjc2] 在某些情况下插件无法进行查询 (#8) 已经出现好几次跳验证的情况了…… jjc1后端从来没有这个问题，建议不要用白板小号或者游客号，把等级提高一点 据说出现这种情况的时候sdk login会返回is_risk=1，你可以自己判断一下 能否添加一个出现 risk 就通知主人的功能？ 你甚至可以自己写！ 这个大概我不会考虑去写因为我无论哪个号都没risk。。。所以没办法测试 如果你pr的话我会很高兴的去merge（ 所以想问问有没有b站这SDK方面的资料提供一下 现有代码无注释是真难啃…… 如果你指的是bsgamesdk大概https://github.com/Kengxxiao/Chika 下就有，如果你指的是chika的注释的话emmm不知道 猛然发现：http://open.biligame.com/wiki/ 那没事了，文档有了。无聊的寒假就来研究研究。 另外chika对付geetest的方法是接入打码平台，不过个人还是倾向不使用过多第三方服务。 当然可以不接入打码平台，自己进验证码页面，像mirai抓包过滑块一样。但是Chika搞这个的目的是掉线重连，所以用了这种自动的方式。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
> > 
> > 
> > geetest也是一个web页面。
> > 可以参考Chika代码里向打码平台请求提供的referer参数，那个就是验证码页面，结果由geetest api返回。
> 
> 确实是web界面，不过刚才我拿f12看了一下，他游戏内验证码界面中的 https://static.biligame.com/sdk/geetest/js/captcha.js 会把geetest的validate结果以`window.webkit.messageHandlers.BiliJsObject.postMessage`的方式返回，这样似乎除了用专用浏览器或者f12打开页面完成验证，还想不到更好的办法把验证传给机器人？（当然指的是管理员手动打开验证界面，不是用第三方服务进行验证处理）
> 
> EDIT: emmmm好像geetest没查referrer。。。。

![image](https://user-images.githubusercontent.com/11478651/107849683-f35ac180-6e37-11eb-9281-0900b2392ffa.png)
可以抓ajax.php的返回

**Comment by qq1176321897** [comment]
05c3753e61ca8c9aa55e4a48ea7208eddec35d5e中已经修改了验证方式，并且提供了私聊进行验证码验证的功能

**Comment by qq1176321897** [comment]
emmmm忘记关了
